# Generated by Django 2.1.15 on 2020-08-06 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Category',
            fields=[
                ('ccid', models.AutoField(primary_key=True, serialize=False)),
                ('c_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course_category',
            },
        ),
        migrations.CreateModel(
            name='Courses_Data',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_disctription', models.TextField(null=True)),
                ('course_duration', models.IntegerField(null=True)),
                ('course_price', models.IntegerField(null=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pl4app.Course_Category')),
            ],
            options={
                'db_table': 'courses_data',
            },
        ),
    ]
